### ISSUE TITLE
[Bug] Cannot create backup

### ISSUE THREAD

**Issue by JiPaix** [AriaMoradi/Tachidesk#1085]
## Device information
- Suwayomi-Server version: v1.1.1-r1598
- Server Operating System: Docker
- Clients: Chrome / Firefox / NodeJS / curl

## Steps to reproduce
1. Start server
2. Go to `http://localhost:4567/settings/backup`
3. Click "Create Backup"

OR

```javascript
// main.js
const response = await fetch("http://localhost:4567/api/v1/backup/export")
response.status //=> 500
```

### Actual behavior
Both `/api/v1/backup/export` and `/api/v1/backup/export/file` are returning an HTTP 500 error code, irrespective of the client used (curl, node, or browser).

## Other details
Console output:
```console
2024-09-15 23:01:28 suwayomi-1  | 23:01:28.333 [DefaultDispatcher-worker-7] WARN io.javalin.Javalin -- Uncaught exception
2024-09-15 23:01:28 suwayomi-1  | java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
2024-09-15 23:01:28 suwayomi-1  |       at kotlinx.serialization.internal.PluginGeneratedSerialDescriptor.getElementDescriptor(PluginGeneratedSerialDescriptor.kt:135)
2024-09-15 23:01:28 suwayomi-1  |       at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeSerializableElement(ProtobufTaggedEncoder.kt:139)
2024-09-15 23:01:28 suwayomi-1  |       at suwayomi.tachidesk.manga.impl.backup.proto.models.Backup.write$Self$server(Backup.kt:9)
2024-09-15 23:01:28 suwayomi-1  |       at suwayomi.tachidesk.manga.impl.backup.proto.models.BackupSerializer.serialize(BackupSerializer.kt:5)
2024-09-15 23:01:28 suwayomi-1  |       at suwayomi.tachidesk.manga.impl.backup.proto.models.BackupSerializer.serialize(BackupSerializer.kt:5)
2024-09-15 23:01:28 suwayomi-1  |       at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:146)
2024-09-15 23:01:28 suwayomi-1  |       at kotlinx.serialization.protobuf.ProtoBuf.encodeToByteArray(ProtoBuf.kt:137)
2024-09-15 23:01:28 suwayomi-1  |       at suwayomi.tachidesk.manga.impl.backup.proto.ProtoBackupExport.createBackup(ProtoBackupExport.kt:192)
2024-09-15 23:01:28 suwayomi-1  |       at suwayomi.tachidesk.manga.controller.BackupController$protobufExportFile$2$1.invokeSuspend(BackupController.kt:114)
2024-09-15 23:01:28 suwayomi-1  |       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-09-15 23:01:28 suwayomi-1  |       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
2024-09-15 23:01:28 suwayomi-1  |       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
2024-09-15 23:01:28 suwayomi-1  |       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
2024-09-15 23:01:28 suwayomi-1  |       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2024-09-15 23:01:28 suwayomi-1  |       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
2024-09-15 23:01:28 suwayomi-1  |       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
2024-09-15 23:01:28 suwayomi-1  |       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
```

**Comment by JiPaix** [comment]
closed by 654a3cc7ed6134afc76be529924317ff5c1f0a9b
