### ISSUE TITLE
[Bug] COLAMANGA cant read manga

### ISSUE THREAD

**Issue by bk1412** [AriaMoradi/Tachidesk#1101]
## Device information
- Suwayomi-Server version: v1.1.1-r1535
- Server Operating System: Ubuntu 23.04
- Server Desktop Environment: N/A
- Server JVM version: Java 8
- Client Operating System: Win10
- Client Web Browser: Google Chrome 129.0.6668.100

## Steps to reproduce
1. open COLAMANGA
2. choose any manga
3. choose any chapter

### Expected behavior
It should be open a comic picture after.

### Actual behavior
cant read,show " Stub!"

## Other details

Same extension test on mihon,everthing is working well

logs:

10月 15 17:10:15 tokyo suwayomi-server[1979945]: 17:10:15.034 [DefaultDispatcher-worker-7] DEBUG notprivacysafe.graphql.execution.Execution -- Executing '9bfbaec9-f257-49b7-80bb-8bf1403c3486' query operation: 'MUTATION' using 'graphql.e>
10月 15 17:10:15 tokyo suwayomi-server[1979945]: 17:10:15.035 [DefaultDispatcher-worker-7] DEBUG graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation -- Dispatching data loaders ([CategoryMetaDataLoader, Last>
10月 15 17:10:15 tokyo suwayomi-server[1979945]: 17:10:15.160 [DefaultDispatcher-worker-16] DEBUG eu.kanade.tachiyomi.network.NetworkHelper -- --> GET https://www.colamanga.com/manga-od825111/1/381.html h2
10月 15 17:10:15 tokyo suwayomi-server[1979945]: 17:10:15.467 [DefaultDispatcher-worker-16] DEBUG eu.kanade.tachiyomi.network.NetworkHelper -- <-- 200 https://www.colamanga.com/manga-od825111/1/381.html (306ms, unknown-length body)
10月 15 17:10:15 tokyo suwayomi-server[1979945]: 17:10:15.472 [DefaultDispatcher-worker-16] ERROR suwayomi.tachidesk.graphql.AsDataFetcherResult -- asDataFetcherResult: failed due to
10月 15 17:10:15 tokyo suwayomi-server[1979945]: java.lang.RuntimeException: Stub!
10月 15 17:10:15 tokyo suwayomi-server[1979945]:         at android.os.Looper.getMainLooper(Looper.java:30)
10月 15 17:10:15 tokyo suwayomi-server[1979945]:         at eu.kanade.tachiyomi.multisrc.colamanga.ColaManga.pageListParse(Unknown Source)

![image](https://github.com/user-attachments/assets/3c574956-665f-4300-9009-4eae9cdafd99)

**Comment by AlanLang** [comment]
I have the same issue

**Comment by Kickunio** [comment]
Did you check in Mihon app if it also appears there? It most likely is a extension problem because COLAMANGA changed something on their website.

**Comment by bk1412** [comment]
> Did you check in Mihon app if it also appears there? It most likely is a extension problem because COLAMANGA changed something on their website.

checked,this extension for Mihon app working normal, that why i think is suwayomi side problem

**Comment by ClydeCode79** [comment]
> > Did you check in Mihon app if it also appears there? It most likely is a extension problem because COLAMANGA changed something on their website.
> 
> checked,this extension for Mihon app working normal, that why i think is suwayomi side problem

How did you add colamamga extension?

**Comment by Robonau** [comment]
> 
> How did you add colamamga extension?

probably from the repo he is using.

**Comment by bk1412** [comment]
just add it from repo list, nothing special



---Original---
From: ***@***.***&gt;
Date: Sun, Nov 24, 2024 22:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Suwayomi/Suwayomi-Server] [Bug] COLAMANGA cant read manga (Issue#1101)




   
Did you check in Mihon app if it also appears there? It most likely is a extension problem because COLAMANGA changed something on their website.
  
checked,this extension for Mihon app working normal, that why i think is suwayomi side problem
  
How did you add colamamga extension?

**Comment by bk1412** [comment]
> > How did you add colamamga extension?
> 
> probably from the repo he is using.
this repo is what i using, anything not right？

**Comment by ClydeCode79** [comment]
> > > How did you add colamamga extension?
> > 
> > 
> > probably from the repo he is using.
> > this repo is what i using, anything not right？

I'm new to mihon transfer from tachiyomi cuz of colamanga and idk or forgot where to get the repo again

**Comment by ClydeCode79** [comment]
> > > How did you add colamamga extension?
> > 
> > 
> > probably from the repo he is using.
> > this repo is what i using, anything not right？

I add the repos but I could not find colamanga even if download it manually it won't show in the extension to search manhua is there something to do more?

**Comment by bk1412** [comment]
> > > > How did you add colamamga extension?
> > > 
> > > 
> > > probably from the repo he is using.
> > > this repo is what i using, anything not right？
> 
> I add the repos but I could not find colamanga even if download it manually it won't show in the extension to search manhua is there something to do more?

in browser page ,filter choose 中文（Chinese）

**Comment by Robonau** [comment]
@Syer10 can u delete the messages with the repo link?

**Comment by ClydeCode79** [comment]
> > > > > How did you add colamamga extension?
> > > > 
> > > > 
> > > > probably from the repo he is using.
> > > > this repo is what i using, anything not right？
> > 
> > 
> > I add the repos but I could not find colamanga even if download it manually it won't show in the extension to search manhua is there something to do more?
> 
> in browser page ,filter choose 中文（Chinese）

Okay thank you it works now

**Comment by ClydeCode79** [comment]
> > > > > How did you add colamamga extension?
> > > > 
> > > > 
> > > > probably from the repo he is using.
> > > > this repo is what i using, anything not right？
> > 
> > 
> > I add the repos but I could not find colamanga even if download it manually it won't show in the extension to search manhua is there something to do more?
> 
> in browser page ,filter choose 中文（Chinese）

I need help like why can't I update all without doing it manually cuz this does not happen when I first started or in tachiyomi 

https://github.com/user-attachments/assets/f35abd73-8ff0-4e80-897d-4aeb05a35105

Also I already transferred my data from tachiyomi to mihon 

Please help me fix this problem

**Comment by Robonau** [comment]
@clydeclamonte79 ask in the mihon discord/github
suwayomi isn't mihon

**Comment by ClydeCode79** [comment]
> @clydeclamonte79 ask in the mihon discord/github suwayomi isn't mihon

Yes I already did and they help me fix and it is working now

**Comment by RTGTX7** [comment]
> > @clydeclamonte79 ask in the mihon discord/github suwayomi isn't mihon
> 
> Yes I already did and they help me fix and it is working now

How you fix it? Are you change to mihon or tachidesk?

**Comment by Robonau** [comment]
> How you fix it? Are you change to mihon or tachidesk?

he is using mihon, as can be seen in the video above

**Comment by RTGTX7** [comment]
I have the same issue and I kindly request that support for COLAMANGA be reintroduced or a workaround be provided to access this source. This will greatly enhance the user experience and broaden the server's compatibility with diverse comic sources.

Device information

Suwayomi-Server version: v1.1.1-r1689 (using Docker stable tag: ghcr.io/suwayomi/tachidesk:stable)
Server Operating System: Docker
Client Operating System: Synology NAS
Client Web Browser: Chrome

Steps to reproduce

Select COLAMANGA (onemanhua) as the source.
Choose any comic to read.
Attempt to load the comic.
Expected behavior The comic should load successfully and display the content.

Actual behavior The application loops loading indefinitely and throws the following error in the logs:

RuntimeException: Stub!

Additional context COLAMANGA is an essential source for many users. However, it appears to require backend support for Android WebView, which Suwayomi-Server currently does not implement (referencing Issue #950). 

I don't like how Mihon works. I prefer using my server to download manga so that I can view it smoothly.

**Comment by spirytuslove** [comment]
这个问题好像是因为缺少chinese-utils-1.0.jar 但我不知道怎么才能加载这个jar

**Comment by spirytuslove** [comment]
> [@clydeclamonte79](https://github.com/clydeclamonte79) ask in the mihon discord/github suwayomi isn't mihon

Is it possible to put chinese-utils-1.0.jar to run on container startup Now many Chinese plugins can't be loaded because of the lack of this jar, such as COLAMANGA.

**Comment by cpiber** [comment]
This also affects other extensions, e.g. Cubari

```
14:52:50.537 [DefaultDispatcher-worker-2] ERROR suwayomi.tachidesk.graphql.AsDataFetcherResult -- asDataFetcherResult: failed due to
java.lang.RuntimeException: Stub!
   at android.os.Looper.getMainLooper(Looper.java:30)
   at eu.kanade.tachiyomi.extension.all.cubari.RemoteStorageUtils$GenericInterceptor.<init>(Unknown Source)
   at eu.kanade.tachiyomi.extension.all.cubari.RemoteStorageUtils$TagInterceptor.<init>(Unknown Source)
   at eu.kanade.tachiyomi.extension.all.cubari.Cubari.fetchSearchManga(Unknown Source)
   at eu.kanade.tachiyomi.source.CatalogueSource$DefaultImpls.getSearchManga(CatalogueSource.kt:41)
   at eu.kanade.tachiyomi.source.online.HttpSource.getSearchManga(HttpSource.kt:28)
   at suwayomi.tachidesk.graphql.mutations.SourceMutation$fetchSourceManga$1.invokeSuspend(SourceMutation.kt:128)
   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
   at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
```

It appears there is no implementation for `android.os.Looper.getMainLooper`

**Comment by Robonau** [comment]
> This also affects other extensions, e.g. Cubari


#161

**Comment by adoyle-h** [comment]
> > [@clydeclamonte79](https://github.com/clydeclamonte79) ask in the mihon discord/github suwayomi isn't mihon
> 
> Yes I already did and they help me fix and it is working now

How do you fix it? Could you please give more details?

**Comment by Robonau** [comment]
> How do you fix it? Could you please give more details?

he didn't, he was using mihon not suwayomi

**Comment by Syer10** [comment]
All the known issues with COLMANGA from our side has been fixed, but it seems currently the extension has problems itself. Wait until the extension updates to test it in Suwayomi

**Comment by boyeye** [comment]
> All the known issues with COLMANGA from our side has been fixed, but it seems currently the extension has problems itself. Wait until the extension updates to test it in Suwayomi我们这边 COLMANGA 的所有已知问题都已修复，但目前扩展程序本身似乎存在问题。请等待扩展程序更新后再在 Suwayomi 中测试。

I've encountered the same issue and tried various solutions. Currently, the only viable temporary fix is to restart the suwayomi container. However, this isn't an ideal solution because the problem of being unable to pull comics reoccurs about half an hour after restarting.
This issue is indeed quite perplexing. If the extension isn't working, why does restarting the container allow it to function normally, only for it to stop working properly again after a while? It's really frustrating!
