### ISSUE TITLE
[Bug] AniList Json error when sending tracking information

### ISSUE THREAD

**Issue by WarDrake** [AriaMoradi/Tachidesk#1181]
## Device information
- Suwayomi-Server version: v1.1.1-r1636
- Server Operating System: Proxmox 8.0.4
- Server Desktop Environment: N/A
- Server JVM version: bundled with docker Image
- Client Operating System: Windows 11
- Client Web Browser: Google Chrome 131.0.6778.85

## Steps to reproduce
1. Login to AniList
2. Read a chapter

### Expected behavior
The chapter should be sent over to the Anilist API

### Actual behavior
The chapter is sent but a JSON error prevents it from working

## Other details
Here's the docker log for the action
suwayomi-1    | 00:19:45.216 [DefaultDispatcher-worker-8] ERROR suwayomi.tachidesk.manga.impl.track.tracker.anilist.Anilist -- loadOAuth err
suwayomi-1    | kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
suwayomi-1    | JSON input:
suwayomi-1    |         at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
suwayomi-1    |         at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
suwayomi-1    |         at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:580)
suwayomi-1    |         at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:578)
suwayomi-1    |         at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:231)
suwayomi-1    |         at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json$default(AbstractJsonLexer.kt:226)
suwayomi-1    |         at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:223)
suwayomi-1    |         at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:79)
suwayomi-1    |         at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:102)
suwayomi-1    |         at suwayomi.tachidesk.manga.impl.track.tracker.anilist.OAuth$$serializer.deserialize(AnilistModels.kt:76)
suwayomi-1    |         at suwayomi.tachidesk.manga.impl.track.tracker.anilist.OAuth$$serializer.deserialize(AnilistModels.kt:76)
suwayomi-1    |         at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
suwayomi-1    |         at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
suwayomi-1    |         at suwayomi.tachidesk.manga.impl.track.tracker.anilist.Anilist.loadOAuth(Anilist.kt:262)
suwayomi-1    |         at suwayomi.tachidesk.manga.impl.track.tracker.anilist.AnilistInterceptor.<init>(AnilistInterceptor.kt:23)
suwayomi-1    |         at suwayomi.tachidesk.manga.impl.track.tracker.anilist.Anilist.interceptor_delegate$lambda$0(Anilist.kt:38)
suwayomi-1    |         at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
suwayomi-1    |         at suwayomi.tachidesk.manga.impl.track.tracker.anilist.Anilist.getInterceptor(Anilist.kt:38)
suwayomi-1    |         at suwayomi.tachidesk.manga.impl.track.tracker.anilist.Anilist.logout(Anilist.kt:228)
suwayomi-1    |         at suwayomi.tachidesk.graphql.mutations.TrackMutation$logoutTracker$2.invokeSuspend(TrackMutation.kt:96)
suwayomi-1    |         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
suwayomi-1    |         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
suwayomi-1    |         at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
suwayomi-1    |         at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
suwayomi-1    |         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
suwayomi-1    |         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
suwayomi-1    |         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
suwayomi-1    |         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
suwayomi-1    | 00:24:09.358 [DefaultDispatcher-worker-3] INFO suwayomi.tachidesk.manga.impl.track.Track -- trackChapter(mangaId= 6303): maxReadChapter= #24.0 Vol.3 Chapter 24: The Thrilling Amusement Park!

logging out and back in to AniList doesn't correct the issue.

**Comment by BenjaminPrice** [comment]
This is still an issue with the latest version.

Suwayomi-Server version: v2.0.1727
Server Operating System: Debian 6.10.9
Server Desktop Environment: N/A
Server JVM version: bundled with docker Image
Client Operating System: Windows 11
Client Web Browser: Arc (Chromium version 135.0.7049.116)

**Comment by schroda** [comment]
your issue is not reproducable

> logging out and back in to AniList doesn't correct the issue.

and logging out and back in again solves the problem when forcibly recreating your problem.

so this looks to be a you problem, especially considering that in all this time that tracking exists, you are the only user to report this issue

**Comment by BenjaminPrice** [comment]
My facing the same issue as OP shows that it wasn't only him. 

That said, I was able to fix it this morning by logging out of everything and deleting the tracking.xml file and logging back in.

**Comment by schroda** [comment]
well..., I blame the time for thinking that you were the op 

![Image](https://github.com/user-attachments/assets/00f7d35d-d884-4415-82ff-327af235672b)

still, one person more doesn't change anything, especially without providing steps to reproduce it

**Comment by himsin** [comment]
@schroda I also encountered this issue after updating from Suwayomi-Server-v1.1.1725 to Suwayomi-Server-v2.0.1727.
Re-login to anilist tracker fixed it. May be you can add a force logout on anilist tracker when this exception occurs and let users know via a UI popup that a re-login is required.
