### ISSUE TITLE
[Bug] Unable to install any extension

### ISSUE THREAD

**Issue by pseudokawaii** [AriaMoradi/Tachidesk#237]
## Device information
- Tachidesk version: v0.5.4-r995
- Server Operating System: Windows 10 21H1 (x64)
- Server Desktop Environment: N/A
- Server JVM version: Java 8 Update 311
- Client Operating System: Windows 10 21H1 (x64)
- Client Web Browser: Firefox 94.0 (64-bit)

## Steps to reproduce
1. Try to install an extension.

### Expected behavior
The extension installs successfully and shows up in the sources tab.

### Actual behavior
The extension doesn't install, it just freezes on 'installing' status.

## Other details
The APK file and jar file for the extension gets created successfully, but the extension still doesn't install. The 'install from external source' feature also doesn't work. So in short, I'm unable to install any extensions. The existing extensions work fine, but when I uninstall an existing extension and try to install it again, it doesn't install.

**Comment by AriaMoradi** [comment]
Don't open the server with external java, use the provided launcher scripts to run Tachidesk.
Read the readme!

More details: 
Use the provided software bundle as intended, if you choose to provide your own JRE, beware that not all JRE distributions are made equally, Check if you have the right version and feature set in your JRE.

**Comment by pseudokawaii** [comment]
> 
> 
> Don't open the server with external java, use the provided launcher scripts to run Tachidesk. Read the readme!

I've always used the external JRE with it, and it worked fine up until the new update (I'm not sure on which specific update the bug was introduced)

**Comment by AriaMoradi** [comment]
> I've always used the external JRE with it, and it worked fine up until the new update (I'm not sure on which specific update the bug was introduced)

We need more info about this issue in order to fix it, which java does it fail to work with, which version introduced the issue.

**Comment by bubu1j** [comment]
same problem here

**Comment by fu4dh4s4n** [comment]
> 
> 
> same problem here

Try the solution mentioned above, it worked for me.

**Comment by dothackjhe** [comment]
I also used to get the same error when running the app using the provided .jar file in the package. Apparently, using the .bat file instead addresses the issue.

**Comment by F-Wer** [comment]
I also got this problem and I got a message in the debug log, that the apk file for the extension couldn't be found.

The problem was that I had a space in my windows user name and Tachidesk couldn't process this. After I changed my username and my user directory it works.

**Comment by jisun692** [comment]
Same Problem Here please fix the issue🥺

**Comment by AriaMoradi** [comment]
This is the fix!

> Don't open the server with external java, use the provided launcher scripts to run Tachidesk.
> Read the readme!

**Comment by metalme** [comment]
Hello, Problem redirected with the same inconvenience, and problem solved when installing temurin and running tachidesk with it instead of Java

**Comment by Samrat-star** [comment]
> Don't open the server with external java, use the provided launcher scripts to run Tachidesk. Read the readme!

Can you pls tell me what that launcher script is? I couldn't find it anywhere.

**Comment by sandip3** [comment]
# extension is not working 
- it keep on loading for hour's
![Screenshot from 2023-08-14 13-41-47](https://github.com/Suwayomi/Tachidesk-Server/assets/81906269/4df08be2-a43d-4ada-98ec-cd2e75f2724a)

**Comment by sandip3** [comment]
# Issue: Tachidesk-Server Extension Not Working - Stuck on Loading Screen

**Description:** The Tachidesk-Server extension is not functioning properly; it remains stuck on the loading screen. I've tried two installation methods, but the issue persists.

## Screenshots:

- Loading screen screenshot:  
  ![Screenshot from 2023-08-14 13-41-47](https://github.com/Suwayomi/Tachidesk-Server/assets/81906269/4df08be2-a43d-4ada-98ec-cd2e75f2724a)

- Hardware specifications screenshot:  
  ![Screenshot from 2023-08-14 13-59-11](https://github.com/Suwayomi/Tachidesk-Server/assets/81906269/4fa5dc07-5062-4b6a-9c2e-9746ae809145)

## Methods Tried:

### Method 1: Using Command Line (CMD)

1. Added PPA repository:
```bash
sudo add-apt-repository ppa:suwayomi/tachidesk-server
```

2. Updated package list:
```bash
sudo apt update
```


3. Installed Tachidesk-Server:
```bash
sudo apt install tachidesk-server

```


### Method 2: Using DEB File

Downloaded DEB file from ![Tachidesk-Server-v0.7.0-r1197-debian-all.deb ](https://github.com/Suwayomi/Tachidesk-Server/releases/download/v0.7.0/Tachidesk-Server-v0.7.0-r1197-debian-all.deb)


#### 📢 Attention: Kindly Respond to and Acknowledge the Issue Request from a Devoted Fan of Your Work 🌟

**Comment by Yuhyeong** [comment]
`20:49:36.313 [DefaultDispatcher-worker-5] ERROR suwayomi.tachidesk.server.JavalinSetup - IOException while handling the request
java.net.ConnectException: Failed to connect to raw.githubusercontent.com/0:0:0:0:0:0:0:0:443
        at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:256)
        at okhttp3.internal.connection.ConnectPlan.connectTcp(ConnectPlan.kt:128)
        at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(FastFallbackExchangeFinder.kt:138)
        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:117)
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.net.ConnectException: Failed to connect to raw.githubusercontent.com/0.0.0.0:443
                ... 9 common frames omitted
        Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
                at java.net.PlainSocketImpl.socketConnect(Native Method)
                at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
                at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
                at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                at java.net.Socket.connect(Socket.java:607)
                at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
                at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:254)
                ... 8 common frames omitted
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:254)
        ... 8 common frames omitted`


I have add proxy, but it doesnt work.

i cant install any extensions 

and im using the scripts u provided.

**Comment by PYUDNG** [comment]
Platform: MacOS Big Sur
It seemed unable to install extensions with custom proxy https certificates, though the root certificate has been installed and trusted in my system, here's the log:
<details>
<code>15:03:41.212 [DefaultDispatcher-worker-4] ERROR suwayomi.tachidesk.server.JavalinSetup - IOException while handling the request
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1356)
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1231)
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1174)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1392)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1300)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
	at okhttp3.internal.connection.ConnectPlan.connectTls(ConnectPlan.kt:323)
	at okhttp3.internal.connection.ConnectPlan.connectTlsEtc(ConnectPlan.kt:188)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.find(FastFallbackExchangeFinder.kt:78)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:267)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:17)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:537)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
	at sun.security.validator.Validator.validate(Validator.java:271)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1340)
	... 29 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
	... 35 common frames omitted
^L^L15:03:47.865 [DefaultDispatcher-worker-7] ERROR suwayomi.tachidesk.server.JavalinSetup - IOException while handling the request
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1356)
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1231)
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1174)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1392)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1300)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
	at okhttp3.internal.connection.ConnectPlan.connectTls(ConnectPlan.kt:323)
	at okhttp3.internal.connection.ConnectPlan.connectTlsEtc(ConnectPlan.kt:188)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.find(FastFallbackExchangeFinder.kt:78)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:267)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:17)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:537)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
	at sun.security.validator.Validator.validate(Validator.java:271)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1340)
	... 29 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
	... 35 common frames omitted
</code></details>

Is there any way to switch off certificate checking or if there will be a fix?

**Comment by stormcalled** [comment]
I also cannot install any new extension. I ran it using the browser launcher and electron launcher as per recommendation of previous commenters. Unfortunately, it still does not work.

**Comment by Robonau** [comment]
> I also cannot install any new extension. I ran it using the browser launcher and electron launcher as per recommendation of previous commenters. Unfortunately, it still does not work.

please don't dig up old/fixed issues
u probably cant install extensions because you haven't added a repo for it to get extensions from

**Comment by stormcalled** [comment]
> > I also cannot install any new extension. I ran it using the browser launcher and electron launcher as per recommendation of previous commenters. Unfortunately, it still does not work.
> 
> please don't dig up old/fixed issues u probably cant install extensions because you haven't added a repo for it to get extensions from

What is a repo?

**Comment by ilnerdchuck** [comment]
Got into this issue while installing trough Docker. 
Trying to install an extension does not produce any log on the docker side, sometimes a pop up triggers with "Could not install the extension", and stays pending in "Installing" then goes back to "Install" 
Meanwhile installing through an apk gives this 
```
22:07:21.416 [DefaultDispatcher-worker-2] WARN android.util.Log -- [Bundle]: Key tachiyomix.contentWarning expected Integer but value was a java.lang.String.  The default value 0 was returned.

22:07:21.475 [DefaultDispatcher-worker-2] WARN android.util.Log -- [Bundle]: Attempt to cast generated internal exception:

java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')

	at android.os.BaseBundle.getInt(BaseBundle.java:914)

	at android.os.BaseBundle.getInt(BaseBundle.java:897)

	at suwayomi.tachidesk.manga.impl.extension.Extension$MetadataProvider$FromPackageInfo.getInt(Extension.kt:279)

	at suwayomi.tachidesk.manga.impl.extension.Extension.installExtension(Extension.kt:401)

	at suwayomi.tachidesk.manga.impl.extension.Extension.installExtension$default(Extension.kt:357)

	at suwayomi.tachidesk.manga.impl.extension.Extension.installExternalExtension(Extension.kt:169)

	at suwayomi.tachidesk.graphql.mutations.ExtensionMutation$installExternalExtension$1.invokeSuspend(ExtensionMutation.kt:182)

	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)

	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)

	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)

	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)

	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:798)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
```
