### ISSUE TITLE
[Bug] Many extensions fails to install with the same error

### ISSUE THREAD

**Issue by NoaHimesaka1873** [AriaMoradi/Tachidesk#279]
## Device information
- Tachidesk version: Tachidesk-Server-v0.6.0-r1048-linux-x64 and aur/tachidesk 0.6.0_r1048-2 (both yields the same result)
- Server Operating System: Arch Linux AMD64
- Server Desktop Environment: Qtile
- Server JVM version: bundled with linux-x64 and OpenJDK 17.0.1 (tried both; same result)
- Client Operating System: Arch Linux AMD64
- Client Web Browser: Mozilla Firefox 95.0.2 and Electron v16.0.4 (both from Arch repository)

## Steps to reproduce
Try to install Bakkin extension (for example)

### Expected behavior
Should have just installed itself

### Actual behavior
Infinite "Installing" loop and error on the console

## Other details
```
23:27:53.214 [DefaultDispatcher-worker-8] WARN  io.javalin.Javalin - Uncaught exception
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at suwayomi.tachidesk.manga.impl.util.PackageTools.loadExtensionSources(PackageTools.kt:152)
	at suwayomi.tachidesk.manga.impl.extension.Extension.installAPK(Extension.kt:144)
	at suwayomi.tachidesk.manga.impl.extension.Extension$installAPK$1.invokeSuspend(Extension.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NoClassDefFoundError: eu/kanade/tachiyomi/BuildConfig
	at eu.kanade.tachiyomi.multisrc.bakkin.BakkinReaderX.<init>(Unknown Source)
	at eu.kanade.tachiyomi.extension.en.bakkin.Bakkin.<init>(Unknown Source)
	... 13 common frames omitted
Caused by: java.lang.ClassNotFoundException: eu.kanade.tachiyomi.BuildConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 15 common frames omitted
```
MangaDex one works fine, Danke furs Lesen, Magical Transations, and Hachirumi fails to install with this exact error.

Also, this program *seriously* needs more verbose logging, the log is too vague and gives little info.

**Comment by AriaMoradi** [comment]
closed in #316
