### ISSUE TITLE
[Bug] Extensions using Guya reader aren't working

### ISSUE THREAD

**Issue by NoaHimesaka1873** [AriaMoradi/Tachidesk#336]
---

## Device information
- Tachidesk version: v0.6.3-r1087
- Server Operating System: Oracle Linux 8.5
- Server Desktop Environment: N/A
- Server JVM version: bundled with docker
- Client Operating System: iPadOS 15.4
- Client Web Browser: Safari whatever version bundled with iPadOS 15.4

## Steps to reproduce
1. Just try to read any chapter from extensions using Guya reader

### Expected behavior
Images should be displayed.

### Actual behavior
Can't load chapter info with the log:
```
23:19:58.537 [DefaultDispatcher-worker-4] WARN  io.javalin.Javalin - Uncaught exception
org.json.JSONException: No value for 
        at org.json.JSONObject.get(JSONObject.java:505)
        at org.json.JSONObject.getJSONArray(JSONObject.java:705)
        at eu.kanade.tachiyomi.multisrc.guya.Guya.parsePageFromJson(Unknown Source)
        at eu.kanade.tachiyomi.multisrc.guya.Guya.pageListParse(Unknown Source)
        at eu.kanade.tachiyomi.multisrc.guya.Guya.access$pageListParse(Unknown Source)
        at eu.kanade.tachiyomi.multisrc.guya.Guya$fetchPageList$2.call(Unknown Source)
        at eu.kanade.tachiyomi.multisrc.guya.Guya$fetchPageList$2.call(Unknown Source)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:34)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda-0(OkHttpExtensions.kt:54)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10423)
        at rx.Observable.subscribe(Observable.java:10390)
        at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:27)
        at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:23)
        at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownload.fetchPageList(ChapterForDownload.kt:71)
        at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownload.asDownloadReady(ChapterForDownload.kt:44)
        at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownloadKt.getChapterDownloadReady(ChapterForDownload.kt:32)
        at suwayomi.tachidesk.manga.controller.MangaController$chapterRetrieve$1.invokeSuspend(MangaController.kt:130)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
        at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
        ... 30 common frames omitted
```

## Other details
They work on normal Tachiyomi. The extension I tested with does not access any Cloudflare or DDoS-Guard backed up IPs nor websites.

**Comment by hoowwshii** [comment]
+1

**Comment by AriaMoradi** [comment]
Issue too old, Create a new issue if this still effects you.
