### ISSUE TITLE
[Bug] tachidesk not launching with jre-19 on arch linux

### ISSUE THREAD

**Issue by DanielJutz** [AriaMoradi/Tachidesk#443]
## Device information
- Tachidesk version: 0.6.5_r1122-2
- Server Operating System: arch linux
- Server Desktop Environment: xfce
- Server JVM version: 19.0.1.u10-3
- Client Operating System: arch linux
- Client Web Browser: firefox

## Steps to reproduce
1. install tachidesk via AUR
2. run `tachidesk` in terminal

### Expected behavior
tachidesk should launch

### Actual behavior
does not launch with the following error
<details>

```
00:37:50.312 [main] INFO  suwayomi.tachidesk.server.ServerSetup - Running Tachidesk v0.6.5 revision r1122
00:37:50.856 [main] INFO  suwayomi.tachidesk.server.util.AppMutex - Mutex status is clear, Resuming startup.
00:37:51.700 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Running migrations on database jdbc:h2:/home/daniel/.local/share/Tachidesk/database
00:37:52.307 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Database version before migrations: 19
00:37:52.309 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Migrations finished successfully
00:37:54.470 [main] WARN  dorkbox.jna.linux.GtkTheme - Unable to get tray image size. Using fallback: 24
00:37:54.754 [main] INFO  dorkbox.systemTray.SystemTray - Successfully loaded
00:37:55.002 [main] INFO  suwayomi.tachidesk.server.util.WebInterfaceManager - WebUI Static files exists and is the correct revision
00:37:55.003 [main] INFO  suwayomi.tachidesk.server.util.WebInterfaceManager - Verifying WebUI Static files...
00:37:55.074 [main] INFO  suwayomi.tachidesk.server.util.WebInterfaceManager - md5: 22894ea18cb97f6d952a03560391ebe3
00:37:55.075 [main] INFO  suwayomi.tachidesk.server.JavalinSetup - Serving web static files for WebUI
00:37:55.125 [main] INFO  io.javalin.Javalin - Static file handler added: StaticFileConfig(hostedPath=/, directory=/home/daniel/.local/share/Tachidesk/webUI, location=EXTERNAL, precompress=false, aliasCheck=null, headers={Cache-Control=max-age=0}, skipFileFunction=(javax.servlet.http.HttpServletRequest) -> kotlin.Boolean). File system location: '/home/daniel/.local/share/Tachidesk/webUI'
00:37:55.161 [main] WARN  io.javalin.Javalin - JDK15 and Kotlin 1.5 break reflection in different ways - the OpenAPI plugin will not work properly. Please visit https://github.com/tipsy/javalin/issues/1193 if you want to help fix this issue.
00:37:55.181 [main] INFO  io.javalin.Javalin - Static file handler added: StaticFileConfig(hostedPath=/, directory=META-INF/resources/webjars, location=CLASSPATH, precompress=false, aliasCheck=null, headers={Cache-Control=max-age=31622400}, skipFileFunction=(javax.servlet.http.HttpServletRequest) -> kotlin.Boolean). File system location: 'jar:file:/usr/share/java/tachidesk-server/Tachidesk-Server.jar!/META-INF/resources/webjars'
00:37:55.185 [main] INFO  io.javalin.Javalin - 
       __                      __ _            __ __
      / /____ _ _   __ ____ _ / /(_)____      / // /
 __  / // __ `/| | / // __ `// // // __ \    / // /_
/ /_/ // /_/ / | |/ // /_/ // // // / / /   /__  __/
\____/ \__,_/  |___/ \__,_//_//_//_/ /_/      /_/

          https://javalin.io/documentation

00:37:55.185 [main] INFO  io.javalin.Javalin - Starting Javalin ...
00:37:55.206 [main] INFO  io.javalin.Javalin - You are running Javalin 4.2.0 (released January 2, 2022. Your Javalin version is 310 days old. Consider checking for a newer version.).
00:37:55.237 [main] INFO  io.javalin.Javalin - Loom is available, using Virtual ThreadPool... Neat!
00:37:55.239 [main] ERROR io.javalin.Javalin - Failed to start Javalin
00:37:55.239 [main] INFO  io.javalin.Javalin - Loom is available, using Virtual ThreadPool... Neat!
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.javalin.core.LoomUtil.getExecutorService(LoomUtil.kt:22)
	at io.javalin.jetty.LoomThreadPool.<init>(JettyUtil.kt:90)
	at io.javalin.jetty.JettyUtil.defaultThreadPool(JettyUtil.kt:28)
	at io.javalin.jetty.JettyUtil.getOrDefault(JettyUtil.kt:20)
	at io.javalin.jetty.JettyServer.server(JettyServer.kt:34)
	at io.javalin.Javalin.start(Javalin.java:181)
	at io.javalin.Javalin.start(Javalin.java:149)
	at io.javalin.Javalin.start(Javalin.java:135)
	at suwayomi.tachidesk.server.JavalinSetup.javalinSetup(JavalinSetup.kt:77)
	at suwayomi.tachidesk.MainKt.main(Main.kt:15)
	at suwayomi.tachidesk.MainKt.main(Main.kt)
Caused by: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview
	at java.base/jdk.internal.misc.PreviewFeatures.ensureEnabled(PreviewFeatures.java:49)
	at java.base/java.lang.Thread.ofVirtual(Thread.java:833)
	at java.base/java.util.concurrent.Executors.newVirtualThreadPerTaskExecutor(Executors.java:274)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 12 more
```

</details>

## Other details
launches fine when installing `jre8-openjdk` and setting it as default with `archlinux-java set java-8-openjdk/jre`

**Comment by Syer10** [comment]
Can you check the preview and see if its any different? Javalin was updated and it may be fixed https://github.com/Suwayomi/Tachidesk-Server-preview/releases/latest

**Comment by DanielJutz** [comment]
Downloaded the preview and executed `tachidesk-server-browser-launcher.sh`. Issue seems to be fixed and Tachidesk launches without issues.

**Comment by Syer10** [comment]
Awesome, it will be fixed in the next release 👍

**Comment by AriaMoradi** [comment]
Tested with `jdk-openjdk 19.0.1.u10-3` on arch and it works
