### ISSUE TITLE
tachidesk cannot browse 18comic aka "禁漫天堂,jinman tiantang" 

### ISSUE THREAD

**Issue by ericvlog** [AriaMoradi/Tachidesk#444]
---

## Device information
- Tachidesk-Server Preview -v0.6.5-r1149 / Tachidesk Deskotp version
- Debian docker and windows 11
- Edge / Chrome

## Steps to reproduce
1. Open tachidesk, go to source, select 禁漫天堂.
2. Select any long comic and open 1st or last chapter 
3. Loading after all it blank.

### Expected behavior
It should be open a comic picture after.

### Actual behavior
it loading and open black blank page.

## Other details
I using debian and install it with docker-compose, and happen as above i descript, then i try download the windows version, test browser mode and electron mode also same, Just extension 18comic or 禁漫天堂 have problem, other extension working great.

I do have android version of tachiyomi, and it working great on the extension.

Hope you can fix it !!

Thanks regard.
![image](https://user-images.githubusercontent.com/64370408/200764861-69b3946f-9733-4e1b-9582-1c810fb6ba4b.png)

**Comment by ericvlog** [comment]
NO more support here?

**Comment by AriaMoradi** [comment]
The extension fails at decoding image files, we have to implement `android.graphics.BitmapFactory.decodeStream` in order to fix this.

```
18:30:30.623 [DefaultDispatcher-worker-6] WARN  io.javalin.Javalin - Uncaught exception
java.lang.RuntimeException: Stub!
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:43)
	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.decodeImage(Unknown Source)
	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.intercept(Unknown Source)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.SpecificHostRateLimitInterceptor.intercept(SpecificHostRateLimitInterceptor.kt:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:28)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:19)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:32)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda$0(OkHttpExtensions.kt:54)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:29)
	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:24)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invokeSuspend(Page.kt:90)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invoke(Page.kt)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invoke(Page.kt)
	at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.getCachedImageResponse(ImageResponse.kt:43)
	at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.getImageResponse(ImageResponse.kt:93)
	at suwayomi.tachidesk.manga.impl.Page.getPageImage(Page.kt:89)
	at suwayomi.tachidesk.manga.impl.Page.getPageImage$default(Page.kt:41)
	at suwayomi.tachidesk.manga.controller.MangaController$pageRetrieve$2$1.invokeSuspend(MangaController.kt:387)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by ericvlog** [comment]
> The extension fails at decoding image files, we have to implement `android.graphics.BitmapFactory.decodeStream` in order to fix this.
> 
> ```
> 18:30:30.623 [DefaultDispatcher-worker-6] WARN  io.javalin.Javalin - Uncaught exception
> java.lang.RuntimeException: Stub!
> 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:43)
> 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.decodeImage(Unknown Source)
> 	at eu.kanade.tachiyomi.extension.zh.jinmantiantang.ScrambledImageInterceptor.intercept(Unknown Source)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at eu.kanade.tachiyomi.network.interceptor.SpecificHostRateLimitInterceptor.intercept(SpecificHostRateLimitInterceptor.kt:45)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at eu.kanade.tachiyomi.network.interceptor.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:28)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:19)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
> 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
> 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:32)
> 	at rx.Subscriber.setProducer(Subscriber.java:211)
> 	at rx.Subscriber.setProducer(Subscriber.java:205)
> 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda$0(OkHttpExtensions.kt:54)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.Observable.subscribe(Observable.java:10423)
> 	at rx.Observable.subscribe(Observable.java:10390)
> 	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:29)
> 	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:24)
> 	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invokeSuspend(Page.kt:90)
> 	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invoke(Page.kt)
> 	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invoke(Page.kt)
> 	at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.getCachedImageResponse(ImageResponse.kt:43)
> 	at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.getImageResponse(ImageResponse.kt:93)
> 	at suwayomi.tachidesk.manga.impl.Page.getPageImage(Page.kt:89)
> 	at suwayomi.tachidesk.manga.impl.Page.getPageImage$default(Page.kt:41)
> 	at suwayomi.tachidesk.manga.controller.MangaController$pageRetrieve$2$1.invokeSuspend(MangaController.kt:387)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
> 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> ```

it mean a fix soon ? it weird because android version tachiyomi is able to browse it.

**Comment by Syer10** [comment]
It depends on how easy it would be to implement image manipulation. Android itself implements it for Tachiyomi to be able to do it, but Tachidesk would have to implement it all by itself or find some kind of shortcut to implement it. It's not a easy thing to do.

**Comment by ericvlog** [comment]
> It depends on how easy it would be to implement image manipulation. Android itself implements it for Tachiyomi to be able to do it, but Tachidesk would have to implement it all by itself or find some kind of shortcut to implement it. It's not a easy thing to do.

Hope you can implement very soon, however thanks for your reply.

**Comment by animeavi** [comment]
> The extension fails at decoding image files, we have to implement `android.graphics.BitmapFactory.decodeStream` in order to fix this.

I don't know if I should open another bug report but I have the same issue on "MangaReader.to", looks related to scrambled pages, to test it look for Vinland Saga and try to read chapter 1.

**Comment by qq280579056** [comment]
老哥 解决了嘛？

**Comment by alinihao** [comment]
I also have this problem。

**Comment by ericvlog** [comment]
hello, how this bug have solve? 

Thanks.

**Comment by jason3232** [comment]
With FlareSolverr setup I am able to get the catalog and index of mangas but it fails to display any image, using the latest preview docker image version of Tachidesk/Suwayomi
```19:49:07.314 [DefaultDispatcher-worker-7] ERROR suwayomi.tachidesk.server.JavalinSetup -- IOException while handling the request
java.io.IOException: java.lang.IllegalArgumentException: no reader for image
        at eu.kanade.tachiyomi.source.online.HttpSource.getImage$suspendImpl(HttpSource.kt:390)
        at eu.kanade.tachiyomi.source.online.HttpSource.getImage(HttpSource.kt)
        at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invokeSuspend(Page.kt:112)
        at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invoke(Page.kt)
        at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invoke(Page.kt)
        at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.getImageResponse(ImageResponse.kt:70)
        at suwayomi.tachidesk.manga.impl.Page.getPageImage(Page.kt:111)
        at suwayomi.tachidesk.manga.impl.Page.getPageImage$default(Page.kt:44)
        at suwayomi.tachidesk.manga.controller.MangaController$pageRetrieve$2$1.invokeSuspend(MangaController.kt:407)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.IOException: java.lang.IllegalArgumentException: no reader for image
        at eu.kanade.tachiyomi.lib.randomua.RandomUserAgentInterceptor.intercept(Unknown Source)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at eu.kanade.tachiyomi.extension.zh.jinmantiantang.UpdateUrlInterceptor.intercept(Unknown Source)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:537)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)```

**Comment by xiaoyaoshengy** [comment]
I have the same problem, but when I use the extension on mihon it can display images normally. I use the latest stable docker image version on Ubuntu, and setup FlareSolverr.

**Comment by ericvlog** [comment]
> I have the same problem, but when I use the extension on mihon it can display images normally. I use the latest stable docker image version on Ubuntu, and setup FlareSolverr.

Dun waste your time, find other apps to use.

**Comment by xiaoyaoshengy** [comment]
> > I have the same problem, but when I use the extension on mihon it can display images normally. I use the latest stable docker image version on Ubuntu, and setup FlareSolverr.
> 
> Dun waste your time, find other apps to use.

Thank you. Could you tell me what you are using now?

**Comment by Robonau** [comment]
just use a different source

**Comment by ericvlog** [comment]
> > > I have the same problem, but when I use the extension on mihon it can display images normally. I use the latest stable docker image version on Ubuntu, and setup FlareSolverr.
> > 
> > 
> > Dun waste your time, find other apps to use.
> 
> Thank you. Could you tell me what you are using now?

https://github.com/Pacalini/PicaComic

here, support windows, android .......

**Comment by Robonau** [comment]
> https://github.com/Pacalini/PicaComic
> 
> here, support windows, android .......

it supports 5 websites and none of them are what this issue is about

**Comment by ericvlog** [comment]
> > https://github.com/Pacalini/PicaComic
> > 
> > here, support windows, android .......
> 
> it supports 5 websites and none of them are what this issue is about

I dun get what you mean, the app in windows support 18comic.

The issue is about unable to browse 18comic, so it is related.

**Comment by Robonau** [comment]
> I dun get what you mean, the app in windows support 18comic.

its not in the list of supported websites on the github

**Comment by ericvlog** [comment]
> > I dun get what you mean, the app in windows support 18comic.
> 
> its not in the list of supported websites on the github
> 

18comic = jingmantiantang, 禁漫天堂

**Comment by Robonau** [comment]
yes, and the list of 6 [supported websites](https://github.com/Pacalini/PicaComic?tab=readme-ov-file#built-in-comic-source) on its github are:
- picacg
- e-hentai/exhentai
- jmcomic
- hitomi
- 绅士漫画
- nhentai

**Comment by ericvlog** [comment]
> yes, and the list of 6 [supported websites](https://github.com/Pacalini/PicaComic?tab=readme-ov-file#built-in-comic-source) on its github are:
> - picacg
> - e-hentai/exhentai
> - jmcomic
> - hitomi
> - 绅士漫画
> - nhentai

Jmcomic is 18comic as well, actually a lot more projects can fix that error, I dun know why here seems no interest to fix it.

But okay is your right.

**Comment by Robonau** [comment]
> Jmcomic is 18comic as well, actually a lot more projects can fix that error, I dun know why here seems no interest to fix it.
> 
> But okay is your right.

ah i didn't know that.
i mean its not a commonly used website, 3 people with the issue in 2 years.
its not an issue that from scratch projects need to fix, it is an issue specific to the way suwayomi uses mihon extensions
suwayomi can't just decide to not use `android.graphics.BitmapFactory.decodeStream` and implementing it would be a ton of work

**Comment by ericvlog** [comment]
> > Jmcomic is 18comic as well, actually a lot more projects can fix that error, I dun know why here seems no interest to fix it.
> > 
> > But okay is your right.
> 
> ah i didn't know that.
> i mean its not a commonly used website, 3 people with the issue in 2 years.
> its not an issue that from scratch projects need to fix, it is an issue specific to the way suwayomi uses mihon extensions
> suwayomi can't just decide to not use `android.graphics.BitmapFactory.decodeStream` and implementing it would be a ton of work

Yup, I understand so I leave a message for him to use other apps instead of waiting our times.

**Comment by cpiber** [comment]
This should be working, since d9c6f52 which implemented the decodeStream. @jason3232 you got a different backtrace, where it could not find a decoder for the image. This would indicate that the image format is not known, we currently support JPEG, PNG, and WEBP. It might be that another format is used. MangaReader should also be working @animeavi

**Comment by Syer10** [comment]
As @cpiber said above, it should be working. If someone runs into new issues feel free to open a new report. If you find unsupported image formats please let us know in the report so we can add support for them.
