### ISSUE TITLE
[Bug] Failed to get extensions from GitHub

### ISSUE THREAD

**Issue by helmiau** [AriaMoradi/Tachidesk#513]
## Device information
- Tachidesk version: **Tachidesk v0.7.0 revision r1205 jar file**
- Server Operating System: **OpenWrt 21.02**
- Server Desktop Environment: **N/A**
- Server JVM version: **OpenJDK for Alpine Linux**
```
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-alpine-r0)
OpenJDK 64-Bit Server VM (build 11.0.18+10-alpine-r0, mixed mode)
```
- Client Operating System: **iPhone 7 iOS 13.3 and Windows 10**
- Client Web Browser: **iOS IPA Sorayomi 0.4.4 and Windows Firefox 110.0.1**

## Steps to reproduce
1. Running a jar file directly from OpenWrt (success) with config below:
```
server.webUIEnabled = false
server.initialOpenInBrowserEnabled = false
server.downloadsPath = "/root/tachidesk"
server.rootDir = "/root/tachidesk"
server.systemTrayEnabled = false
```
2. When client browse an extension, log said:
```
root@HelmiWrt $~ java -Dsuwayomi.tachidesk.config.server.rootDir="/root/tachidesk" -jar /root/tachidesk/tachidesk.jar
01:48:05.542 [main] INFO  suwayomi.tachidesk.server.ServerSetup - Running Tachidesk v0.7.0 revision r1205
01:48:06.671 [main] INFO  suwayomi.tachidesk.server.util.AppMutex - Mutex status is clear, Resuming startup.
01:48:07.862 [main] INFO  suwayomi.tachidesk.server.database.DBManager - Using h2 database version 1.4
01:48:08.495 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Running migrations on database jdbc:h2:/root/tachidesk/database
01:48:10.225 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Database version before migrations: 25
01:48:10.231 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Migrations finished successfully
01:48:11.388 [main] INFO  io.javalin.Javalin -
       __                      __ _            __ __
      / /____ _ _   __ ____ _ / /(_)____      / // /
 __  / // __ `/| | / // __ `// // // __ \    / // /_
/ /_/ // /_/ / | |/ // /_/ // // // / / /   /__  __/
\____/ \__,_/  |___/ \__,_//_//_//_/ /_/      /_/

          https://javalin.io/documentation

01:48:11.410 [main] INFO  io.javalin.Javalin - Starting Javalin ...
01:48:11.469 [main] INFO  io.javalin.Javalin - You are running Javalin 4.6.6 (released October 2, 2022. Your Javalin version is 155 days old. Consider checking for a newer version.).
01:48:11.936 [main] INFO  io.javalin.Javalin - Listening on http://0.0.0.0:4567/
01:48:11.937 [main] INFO  io.javalin.Javalin - Javalin started in 120ms \o/
01:49:07.512 [JettyServerThreadPool-29] INFO  suwayomi.tachidesk.manga.impl.update.UpdaterSocket - 31c9126e-ac49-47ff-9a78-38c61efbd740
01:49:12.479 [DefaultDispatcher-worker-1] ERROR suwayomi.tachidesk.manga.impl.extension.github.ExtensionGithubApi - Failed to get extensions from GitHub
javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1690)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:471)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
        at okhttp3.internal.connection.ConnectPlan.connectTls(ConnectPlan.kt:323)
        at okhttp3.internal.connection.ConnectPlan.connectTlsEtc(ConnectPlan.kt:188)
        at okhttp3.internal.connection.FastFallbackExchangeFinder.find(FastFallbackExchangeFinder.kt:78)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:267)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:17)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:537)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:102)
        at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
        at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:300)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:189)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
        ... 20 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
        at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
        at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
        at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:99)
        ... 36 common frames omitted

```

## Other details
When client open browse tab, the app should show the lists of extensions, but at this condition Sorayomi show error **status code: 500**, what should i do?

**Comment by AriaMoradi** [comment]
Your java installation is missing ca certificates, figure out how to fix it through your distro or use another distro for hosting the server.

OpenWrt is an embedded linux, probaly they didn't include it to decrease size. You might run into further issues down the line for the same reason.

**Comment by helmiau** [comment]
> Your java installation is missing ca certificates, figure out how to fix it through your distro or use another distro for hosting the server.
> 
> OpenWrt is an embedded linux, probaly they didn't include it to decrease size. You might run into further issues down the line for the same reason.

can you help me with package(s) should i add?
