### ISSUE TITLE
[Bug] downloadAsCbz Will Throw Error While Downloading New Manga

### ISSUE THREAD

**Issue by pratimes** [AriaMoradi/Tachidesk#550]
Steps:

- Enable `downloadAsCbz` in conf file
- Select new manga to download
- `error` will come in UI

Error stack -
```
22:45:33.560 [DefaultDispatcher-worker-1] ←[39mDEBUG←[0;39m suwayomi.tachidesk.manga.impl.download.DownloadManager - Added chapter 12 to download queue (Jujutsu Kaisen | #222 - Chapter 222: Foretokens)
22:45:34.082 [DefaultDispatcher-worker-1] ←[34mINFO ←[0;39m suwayomi.tachidesk.manga.impl.download.DownloadManager - Running: 0
May 20, 2023 10:45:34 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://jumpg-webapi.tokyo-cdn.com/api/manga_viewer?chapter_id=1016659&split=yes&img_quality=super_high&format=json
May 20, 2023 10:45:34 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://jumpg-webapi.tokyo-cdn.com/api/manga_viewer?chapter_id=1016659&split=yes&img_quality=super_high&format=json (244ms, unknown-length body)
22:45:34.657 [DefaultDispatcher-worker-5] ←[34mINFO ←[0;39m suwayomi.tachidesk.manga.impl.download.Downloader - Downloader faced an exception
java.io.IOException: The system cannot find the path specified
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1023)
        at suwayomi.tachidesk.manga.impl.download.ArchiveProvider$download$2.invokeSuspend(ArchiveProvider.kt:37)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
May 20, 2023 10:45:34 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://jumpg-webapi.tokyo-cdn.com/api/manga_viewer?chapter_id=1016659&split=yes&img_quality=super_high&format=json
May 20, 2023 10:45:35 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://jumpg-webapi.tokyo-cdn.com/api/manga_viewer?chapter_id=1016659&split=yes&img_quality=super_high&format=json (671ms, unknown-length body)
22:45:35.620 [DefaultDispatcher-worker-5] ←[34mINFO ←[0;39m suwayomi.tachidesk.manga.impl.download.Downloader - Downloader faced an exception
java.io.IOException: The system cannot find the path specified
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1023)
        at suwayomi.tachidesk.manga.impl.download.ArchiveProvider$download$2.invokeSuspend(ArchiveProvider.kt:37)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
May 20, 2023 10:45:35 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://jumpg-webapi.tokyo-cdn.com/api/manga_viewer?chapter_id=1016659&split=yes&img_quality=super_high&format=json
May 20, 2023 10:45:36 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://jumpg-webapi.tokyo-cdn.com/api/manga_viewer?chapter_id=1016659&split=yes&img_quality=super_high&format=json (800ms, unknown-length body)
May 20, 2023 10:45:36 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://mangaplus.shueisha.co.jp/drm/title/100145/title_thumbnail_portrait_list/159766.jpg?key=9ea72c833bad0d42412819e3e098b5f2&duration=86400 (3938ms, 36670-byte body)
May 20, 2023 10:45:36 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://mangaplus.shueisha.co.jp/drm/title/100218/title_thumbnail_portrait_list/249245.jpg?key=b4c6889b2aeb5c39a9825872fce71263&duration=86400
22:45:36.759 [DefaultDispatcher-worker-5] ←[34mINFO ←[0;39m suwayomi.tachidesk.manga.impl.download.Downloader - Downloader faced an exception
java.io.IOException: The system cannot find the path specified
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1023)
        at suwayomi.tachidesk.manga.impl.download.ArchiveProvider$download$2.invokeSuspend(ArchiveProvider.kt:37)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
22:45:37.106 [DefaultDispatcher-worker-3] ←[34mINFO ←[0;39m suwayomi.tachidesk.manga.impl.download.DownloadManager - Running: 0
```

Note - If folder exists in download location, it will not fail.

**Comment by AriaMoradi** [comment]
please open another issue and include all the required information.

**Comment by pratimes** [comment]
what information is missing? I gave steps and error stack..that should work.

**Comment by Robonau** [comment]
> what information is missing?

the information that is asked for in the issue template
