### ISSUE TITLE
[Bug] tachidesk cannot download chapters from Baozi Manhua aka 包子漫画 (ZH)

### ISSUE THREAD

**Issue by vuhe** [AriaMoradi/Tachidesk#686]
## Device information
- Tachidesk version: v0.7.0-docker
- Server Operating System: macOS 13.5.1
- Server Desktop Environment: Docker 24.0.6
- Server JVM version: bundled with docker
- Client Operating System: macOS 13.5.1
- Client Web Browser: Safari 16.6

## Steps to reproduce
1. Install Baozi Manhua extensions.
2. Open tachidesk, go to source, select 包子漫画.
3. Select any long comic and open 1st or last chapter, download chapter.

### Expected behavior
It should download the chapter correctly.

### Actual behavior
It indicates that the download is in progress and has stopped at 6%, and the log shows that the method cannot be found.

## Other details
This extension will process the image and delete the banner when downloading it. From the log, it seems that it called the `void android.graphics.Bitmap.getPixels(int[], int, int, int, int, int, int)` method but no call was found.

Log output:
```
01:09:34.285 [DefaultDispatcher-worker-7] [34mINFO [0;39m suwayomi.tachidesk.manga.impl.download.DownloadManager - Running: 0
Exception in thread "DefaultDispatcher-worker-4" java.lang.NoSuchMethodError: 'void android.graphics.Bitmap.getPixels(int[], int, int, int, int, int, int)'
	at com.github.stevenyomi.baozibanner.BannerChecker$bannerBuffer$2.invoke(Unknown Source)
	at com.github.stevenyomi.baozibanner.BannerChecker$bannerBuffer$2.invoke(Unknown Source)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.github.stevenyomi.baozibanner.BannerChecker.getBannerBuffer(Unknown Source)
	at com.github.stevenyomi.baozibanner.BannerChecker.check$library_release(Unknown Source)
	at com.github.stevenyomi.baozibanner.BaoziBanner.intercept(Unknown Source)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:19)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:32)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda$0(OkHttpExtensions.kt:54)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:29)
	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:24)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invokeSuspend(Page.kt:99)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invoke(Page.kt)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invoke(Page.kt)
	at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.getCachedImageResponse(ImageResponse.kt:53)
	at suwayomi.tachidesk.manga.impl.Page.getPageImage(Page.kt:98)
	at suwayomi.tachidesk.manga.impl.download.FolderProvider.download(FolderProvider.kt:48)
	at suwayomi.tachidesk.manga.impl.ChapterDownloadHelper.download(ChapterDownloadHelper.kt:30)
	at suwayomi.tachidesk.manga.impl.download.Downloader.run(Downloader.kt:94)
	at suwayomi.tachidesk.manga.impl.download.Downloader.access$run(Downloader.kt:34)
	at suwayomi.tachidesk.manga.impl.download.Downloader$start$1.invokeSuspend(Downloader.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2a63931d, Dispatchers.Default]
01:09:38.291 [DefaultDispatcher-worker-7] [34mINFO [0;39m suwayomi.tachidesk.manga.impl.download.DownloadManager - Running: 0
01:09:39.297 [DefaultDispatcher-worker-8] [34mINFO [0;39m suwayomi.tachidesk.manga.impl.download.DownloadManager - Running: 0
01:09:40.300 [DefaultDispatcher-worker-6] [34mINFO [0;39m suwayomi.tachidesk.manga.impl.download.DownloadManager - Running: 0
01:09:41.303 [DefaultDispatcher-worker-8] [34mINFO [0;39m suwayomi.tachidesk.manga.impl.download.DownloadManager - Running: 0
01:09:42.307 [DefaultDispatcher-worker-4] [34mINFO [0;39m suwayomi.tachidesk.manga.impl.download.DownloadManager - Running: 0
01:09:43.309 [DefaultDispatcher-worker-8] [34mINFO [0;39m suwayomi.tachidesk.manga.impl.download.DownloadManager - Running: 0
01:09:44.313 [DefaultDispatcher-worker-7] [34mINFO [0;39m suwayomi.tachidesk.manga.impl.download.DownloadManager - Running: 0
```

If my word is strange, it's because I used translation software.

**Comment by Syer10** [comment]
@animeavi would you like to take a look at this? Since you contributed all the bitmap manipulation code.

**Comment by vuhe** [comment]
This may be helpful as I have found the [library](https://github.com/stevenyomi/baozibanner) that this extension uses for manipulating images.

Use at [there](https://github.com/stevenyomi/baozibanner/blob/9ac9b08e1d84215c19a4ea06c126860bb6093bbd/library/src/main/kotlin/com/github/stevenyomi/baozibanner/BannerChecker.kt#L33).

> If my word is strange, it's because I used translation software.
