### ISSUE TITLE
[Bug] Madokami extension not working

### ISSUE THREAD

**Issue by CatPlanet** [AriaMoradi/Tachidesk#770]
## Device information
- Tachidesk version: Tachidesk v0.7.0 revision r1197 ( Tachidesk-Server-v0.7.0-r1197-windows-x64.zip )
- Server Operating System: Windows 7
- Server Desktop Environment: N/A
- Server JVM version: bundled ( openjdk version "1.8.0_302" )
- Client Operating System: Windows 7
- Client Web Browser: Firefox 115.4.0esr

## Steps to reproduce
0. Be logged to Madokami in browser
1. Install Madokami extension
2. Try to use it **any** way
3. Nothing ever happens

### Expected behavior
Recent manga list. A title to download. Something.

### Actual behavior
Nothing happens. From debug log:

> INFO: --> GET https://manga.madokami.al/recent
> Nov 13, 2023 9:27:16 PM okhttp3.internal.platform.Platform log
> INFO: <-- HTTP FAILED: java.io.IOException: You are currently logged out.
> Go to Extensions > Details to input your credentials.
> 21:27:16.098 [DefaultDispatcher-worker-2] [1;31mERROR[0;39m suwayomi.tachidesk.server.JavalinSetup - IOException while handling the request
> java.io.IOException: You are currently logged out.
> Go to Extensions > Details to input your credentials.
>         at eu.kanade.tachiyomi.extension.en.madokami.Madokami$special$$inlined$_addInterceptor$1.intercept(Unknown Source)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>         at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:233)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>         at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:19)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>         at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
>         at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
>         at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:32)
>         at rx.Subscriber.setProducer(Subscriber.java:211)
>         at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
>         at rx.Subscriber.setProducer(Subscriber.java:205)
>         at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda$0(OkHttpExtensions.kt:54)
>         at rx.Observable.unsafeSubscribe(Observable.java:10327)
>         at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
>         at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
>         at rx.Observable.unsafeSubscribe(Observable.java:10327)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.Observable.subscribe(Observable.java:10423)
>         at rx.Observable.subscribe(Observable.java:10390)
>         at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:29)
>         at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:24)
>         at suwayomi.tachidesk.manga.impl.MangaList.getMangaList(MangaList.kt:36)
>         at suwayomi.tachidesk.manga.controller.SourceController$popular$2$1.invokeSuspend(SourceController.kt:78)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>         at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
>         at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

## Other details
"Go to Extensions > Details to input your credentials." hint is really useless if there is no way to input credentials. There is only uninstall button.
I've looked through wiki, config file, local files in search for more configs but there is nothing.
I couldn't find extension-related configuration entries in h2 database file as well.
I skimmed through source code but again, couldn't find anything helpful.

Help would be appreciated.

**Comment by CatPlanet** [comment]
My bad, credentials options are hidden in sources -> click on borked extension then the small setting icon apprears when I can put credentials.
