### ISSUE TITLE
[Bug] ReadComicOnline chapter page load fails

### ISSUE THREAD

**Issue by schroda** [AriaMoradi/Tachidesk#771]
## Steps to reproduce
1. Open the reader for a ReadComicOnline entry

### Expected behavior
Pages load

### Actual behavior
Loading of pages fails

## Other details
Discord support thread https://discord.com/channels/801021177333940224/1130668544300953673

logs from latest preview (r1424):
```
2023-11-18 11:50:00.470 [DefaultDispatcher-worker-35] WARN  notprivacysafe.graphql.execution.SimpleDataFetcherExceptionHandler - Exception while fetching data (/fetchChapterPages) : syntax error in eval at line number 0 at column number 65364
app.cash.quickjs.QuickJsException: syntax error in eval at line number 0 at column number 65364
	at app.cash.quickjs.QuickJs.evaluate(QuickJs.java:30)
	at eu.kanade.tachiyomi.lib.synchrony.Deobfuscator.deobfuscateScript(Unknown Source)
	at eu.kanade.tachiyomi.extension.en.readcomiconline.Readcomiconline$rguardBytecode$2.invoke(Unknown Source)
	at eu.kanade.tachiyomi.extension.en.readcomiconline.Readcomiconline$rguardBytecode$2.invoke(Unknown Source)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at eu.kanade.tachiyomi.extension.en.readcomiconline.Readcomiconline.getRguardBytecode(Unknown Source)
	at eu.kanade.tachiyomi.extension.en.readcomiconline.Readcomiconline.urlDecode(Unknown Source)
	at eu.kanade.tachiyomi.extension.en.readcomiconline.Readcomiconline.pageListParse(Unknown Source)
	at eu.kanade.tachiyomi.source.online.ParsedHttpSource.pageListParse(ParsedHttpSource.kt:180)
	at eu.kanade.tachiyomi.source.online.HttpSource$fetchPageList$1.invoke(HttpSource.kt:325)
	at eu.kanade.tachiyomi.source.online.HttpSource$fetchPageList$1.invoke(HttpSource.kt:324)
	at eu.kanade.tachiyomi.source.online.HttpSource.fetchPageList$lambda$8(HttpSource.kt:324)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:36)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda$0(OkHttpExtensions.kt:56)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:28)
	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:22)
	at eu.kanade.tachiyomi.source.online.HttpSource.getPageList$suspendImpl(HttpSource.kt:317)
	at eu.kanade.tachiyomi.source.online.HttpSource.getPageList(HttpSource.kt)
	at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownload.fetchPageList(ChapterForDownload.kt:104)
	at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownload.asDownloadReady(ChapterForDownload.kt:62)
	at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownloadKt.getChapterDownloadReady(ChapterForDownload.kt:39)
	at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownloadKt.getChapterDownloadReady$default(ChapterForDownload.kt:32)
	at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownloadKt.getChapterDownloadReadyById(ChapterForDownload.kt:43)
	at suwayomi.tachidesk.graphql.mutations.ChapterMutation$fetchChapterPages$1.invokeSuspend(ChapterMutation.kt:215)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: javax.script.ScriptException: syntax error in eval at line number 0 at column number 65364
	at org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:122)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at app.cash.quickjs.QuickJs.evaluate(QuickJs.java:27)
	... 46 common frames omitted
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 34 common frames omitted
```

**Comment by Syer10** [comment]
I am going to close this, since while I got the JS working in https://github.com/Suwayomi/Suwayomi-Server/pull/793. It has since been replaced by a Webview solution which is unsupported by Suwayomi

**Comment by barrelltitor** [comment]
So this extension will not work or what are the steps to get it working?

**Comment by Robonau** [comment]
> So this extension will not work or what are the steps to get it working?

it is working in preview that has webview
