### ISSUE TITLE
[Bug] Lectormanga & Tumangaonline no download

### ISSUE THREAD

**Issue by TheDoom95** [AriaMoradi/Tachidesk#774]
## Device information
- Tachidesk version: preview (r1424)
- Server Operating System: Windows 10 Pro 22h2
- Server JVM version: Java(TM) SE Runtime Environment (build 20.0.1+9-29)
- Client Web Browser:  Google Chrome 119.0.6045.160

## Steps to reproduce
When downloading a manga from **Lectormanga** and **Tumangaonline**

### Expected behavior
Download the pages and save them on my local computer.

### Actual behavior
No download

## Other details
Archive log:
[application.log](https://github.com/Suwayomi/Tachidesk-Server/files/13401881/application.log)

fragment of error
```
2023-11-19 02:21:11.900 [DefaultDispatcher-worker-5] WARN  suwayomi.tachidesk.manga.impl.download.Downloader source(7925520943983324764) - downloadChapter(Mahou Sensei Negima!  (153) - Capítulo 1.00 | ¡El pequeño profesor es un mago! (49) | state= Error, tries= 1, progress= 0.0)) - failed due to
java.io.IOException: canceled due to java.lang.RuntimeException: Stub!
	at eu.kanade.tachiyomi.source.online.HttpSource.getImage$suspendImpl(HttpSource.kt:391)
	at eu.kanade.tachiyomi.source.online.HttpSource.getImage(HttpSource.kt)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invokeSuspend(Page.kt:112)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invoke(Page.kt)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$5.invoke(Page.kt)
	at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.getImageResponse(ImageResponse.kt:70)
	at suwayomi.tachidesk.manga.impl.Page.getPageImage(Page.kt:111)
	at suwayomi.tachidesk.manga.impl.download.fileProvider.ChaptersFilesProvider.downloadImpl$suspendImpl(ChaptersFilesProvider.kt:42)
	at suwayomi.tachidesk.manga.impl.download.fileProvider.ChaptersFilesProvider.downloadImpl(ChaptersFilesProvider.kt)
	at suwayomi.tachidesk.manga.impl.download.fileProvider.impl.FolderProvider.downloadImpl(FolderProvider.kt:33)
	at suwayomi.tachidesk.manga.impl.download.fileProvider.ChaptersFilesProvider$download$1.execute(ChaptersFilesProvider.kt:69)
	at suwayomi.tachidesk.manga.impl.download.fileProvider.ChaptersFilesProvider$download$1.execute(ChaptersFilesProvider.kt:69)
	at suwayomi.tachidesk.manga.impl.ChapterDownloadHelper.download(ChapterDownloadHelper.kt:37)
	at suwayomi.tachidesk.manga.impl.download.Downloader.run(Downloader.kt:129)
	at suwayomi.tachidesk.manga.impl.download.Downloader.access$run(Downloader.kt:33)
	at suwayomi.tachidesk.manga.impl.download.Downloader$run$1.invokeSuspend(Downloader.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.IOException: canceled due to java.lang.RuntimeException: Stub!
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:550)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
	Suppressed: java.lang.RuntimeException: Stub!
		at android.os.Looper.getMainLooper(Looper.java:30)
		at eu.kanade.tachiyomi.extension.es.lectormanga.LectorManga$special$$inlined$_addInterceptor$1.intercept(Unknown Source)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:119)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:233)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:18)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:537)
		... 3 common frames omitted
2023-11-19 02:21:14.974 [OkHttp Dispatcher] ERROR suwayomi.tachidesk.server.ServerSetup - unhandled exception
java.lang.RuntimeException: Stub!
	at android.os.Looper.getMainLooper(Looper.java:30)
	at eu.kanade.tachiyomi.extension.es.lectormanga.LectorManga$special$$inlined$_addInterceptor$1.intercept(Unknown Source)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:119)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:233)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:18)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:537)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by Syer10** [comment]
Both TuMangaOnline and LectorManga use a background webview to load the site initially, this is not supported by Tachidesk currently.

**Comment by cpiber** [comment]
Seems to be fixed, since neither of them uses WebView anymore
