### ISSUE TITLE
[Bug] failed to set cookies for a extension, and a date time error occur in another extion

### ISSUE THREAD

**Issue by Yuhyeong** [AriaMoradi/Tachidesk#789]
## Cookies Problem
when i updating my manga, the exception occurs.

```sh
15:54:25.690 [DefaultDispatcher-worker-1] INFO  android.util.Log - [ERROR] Mangabz: failed to set cookie
java.lang.RuntimeException: Stub!
	at android.webkit.CookieManager.getInstance(CookieManager.java:28)
	at eu.kanade.tachiyomi.extension.zh.mangabz.CookieInterceptor.setCookie(Unknown Source)
	at eu.kanade.tachiyomi.extension.zh.mangabz.CookieInterceptor.intercept(Unknown Source)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:19)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:32)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda$0(OkHttpExtensions.kt:54)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:29)
	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:24)
	at suwayomi.tachidesk.manga.impl.Chapter.getSourceChapters(Chapter.kt:67)
	at suwayomi.tachidesk.manga.impl.Chapter.getChapterList(Chapter.kt:44)
	at suwayomi.tachidesk.manga.impl.update.Updater.process(Updater.kt:53)
	at suwayomi.tachidesk.manga.impl.update.Updater.access$process(Updater.kt:22)
	at suwayomi.tachidesk.manga.impl.update.Updater$createUpdateChannel$1.invokeSuspend(Updater.kt:37)
	at suwayomi.tachidesk.manga.impl.update.Updater$createUpdateChannel$1.invoke(Updater.kt)
	at suwayomi.tachidesk.manga.impl.update.Updater$createUpdateChannel$1.invoke(Updater.kt)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```
## Date time problem
```sh
ERROR suwayomi.tachidesk.manga.impl.update.Updater - Error while updating 进击的巨人
java.lang.RuntimeException: Stub!
	at android.text.format.DateFormat.format(DateFormat.java:41)
	at eu.kanade.tachiyomi.extension.zh.manhuaren.Manhuaren.myRequest(Unknown Source)
	at eu.kanade.tachiyomi.extension.zh.manhuaren.Manhuaren.myPost(Unknown Source)
	at eu.kanade.tachiyomi.extension.zh.manhuaren.Manhuaren.getAnonyUser(Unknown Source)
	at eu.kanade.tachiyomi.extension.zh.manhuaren.Manhuaren.fetchToken(Unknown Source)
	at eu.kanade.tachiyomi.extension.zh.manhuaren.Manhuaren.access$fetchToken(Unknown Source)
	at eu.kanade.tachiyomi.extension.zh.manhuaren.Manhuaren$token$2.invoke(Unknown Source)
	at eu.kanade.tachiyomi.extension.zh.manhuaren.Manhuaren$token$2.invoke(Unknown Source)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at eu.kanade.tachiyomi.extension.zh.manhuaren.Manhuaren.getToken(Unknown Source)
	at eu.kanade.tachiyomi.extension.zh.manhuaren.Manhuaren.myGet(Unknown Source)
	at eu.kanade.tachiyomi.extension.zh.manhuaren.Manhuaren.mangaDetailsRequest(Unknown Source)
	at eu.kanade.tachiyomi.extension.zh.manhuaren.Manhuaren.chapterListRequest(Unknown Source)
	at eu.kanade.tachiyomi.source.online.HttpSource.fetchChapterList(HttpSource.kt:213)
	at suwayomi.tachidesk.manga.impl.Chapter.getSourceChapters(Chapter.kt:67)
	at suwayomi.tachidesk.manga.impl.Chapter.getChapterList(Chapter.kt:44)
	at suwayomi.tachidesk.manga.impl.update.Updater.process(Updater.kt:53)
	at suwayomi.tachidesk.manga.impl.update.Updater.access$process(Updater.kt:22)
	at suwayomi.tachidesk.manga.impl.update.Updater$createUpdateChannel$1.invokeSuspend(Updater.kt:37)
	at suwayomi.tachidesk.manga.impl.update.Updater$createUpdateChannel$1.invoke(Updater.kt)
	at suwayomi.tachidesk.manga.impl.update.Updater$createUpdateChannel$1.invoke(Updater.kt)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by Syer10** [comment]
The first one is fixed in the preview version
