### ISSUE TITLE
[Bug] Mangadex 404 error on manga page

### ISSUE THREAD

**Issue by luevano** [AriaMoradi/Tachidesk#797]
## Device information
- Tachidesk version: 0.7.0_r1197-1 (from AUR)
- Server Operating System: Arch Linux 6.6.7.arch1-1
- Server Desktop Environment: N/A
- Server JVM version: jdk-openjdk 21.u35-8
- Client Operating System: Windows 11
- Client Web Browser: Firefox 121.0 (64-bit)

## Steps to reproduce

1. Fresh Tachidesk install.
2. Add Mangadex extension.
3. Go to source section.
4. Click Mangadex.
5. Select any manga.
6. [Bug] Not working.

### Expected behavior
Should load manga information, chapters, etc.

### Actual behavior
Shows the following:

(･o･;)
Could not load manga
Request failed with status code 404

## Other details
Other extensions (such as mangapill) works.
Related issue (closed): #646 and having same issue as: https://github.com/Suwayomi/Tachidesk-Server/issues/646#issuecomment-1763221832

Logs (this repeats a few times):

```
10:05:30.689 [DefaultDispatcher-worker-5] ERROR suwayomi.tachidesk.server.JavalinSetup - NullPointerException while handling the request
java.lang.NullPointerException: null
        at java.base/java.io.Reader.<init>(Reader.java:168)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:108)
        at eu.kanade.tachiyomi.lib.i18n.Intl.createBundle(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl.access$createBundle(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl$baseBundle$2.invoke(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl$baseBundle$2.invoke(Unknown Source)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at eu.kanade.tachiyomi.lib.i18n.Intl.getBaseBundle(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl.access$getBaseBundle(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl$bundle$2.invoke(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl$bundle$2.invoke(Unknown Source)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at eu.kanade.tachiyomi.lib.i18n.Intl.getBundle(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl.get(Unknown Source)
        at eu.kanade.tachiyomi.extension.all.mangadex.MangaDexHelper.createManga(Unknown Source)
        at eu.kanade.tachiyomi.extension.all.mangadex.MangaDex.mangaDetailsParse(Unknown Source)
        at eu.kanade.tachiyomi.source.online.HttpSource$fetchMangaDetails$1.invoke(HttpSource.kt:184)
        at eu.kanade.tachiyomi.source.online.HttpSource$fetchMangaDetails$1.invoke(HttpSource.kt:183)
        at eu.kanade.tachiyomi.source.online.HttpSource.fetchMangaDetails$lambda$4(HttpSource.kt:183)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:34)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda$0(OkHttpExtensions.kt:54)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10423)
        at rx.Observable.subscribe(Observable.java:10390)
        at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:29)
        at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:24)
        at suwayomi.tachidesk.manga.impl.Manga.getManga(Manga.kt:72)
        at suwayomi.tachidesk.manga.controller.MangaController$retrieve$2$1.invokeSuspend(MangaController.kt:48)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
        at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
        ... 28 common frames omitted
```

**Comment by Syer10** [comment]
This has been fixed in the preview version. Update to preview or wait for the next stable version and re-install the Mangadex extension.

**Comment by luevano** [comment]
@Syer10 any idea on when it might release? just checked and I see that the last stable release was on Feb 12

**Comment by Syer10** [comment]
We've been looking at getting a release out relatively soon, within the next 2-3 weeks

**Comment by luevano** [comment]
Gotcha, thanks, will wait then. Finally, is the name change of the project expected for this release? asking so I can prepare for that

**Comment by Syer10** [comment]
Yes, #795 is going to be included
