### ISSUE TITLE
[Bug] Failed to get extensions from GitHub

### ISSUE THREAD

**Issue by wiredmatt** [AriaMoradi/Tachidesk#886]
## Device information
- Suwayomi-Server version: Latest
- Server Operating System: N/A
- Server Desktop Environment: N/A
- Server JVM version: OpenJDK latest
- Client Operating System: Any
- Client Web Browser: Any

## Steps to reproduce
1. Launch the frontend (either electron or browser, whatever)
2. Go to the extensions tab

### Expected behavior
The extensions list should be loaded

### Actual behavior
The extensions list are not loaded

## Other details

```
22:25:39.115 [DefaultDispatcher-worker-6] ERROR suwayomi.tachidesk.manga.impl.extension.github.ExtensionGithubApi - Failed to get extensions from GitHub
eu.kanade.tachiyomi.network.HttpException: HTTP error 404
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:65)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Feb 20, 2024 10:25:39 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://gcore.jsdelivr.net/gh/tachiyomiorg/tachiyomi-extensions@repo/index.min.json
Feb 20, 2024 10:25:39 PM okhttp3.internal.platform.Platform log
INFO: <-- 404 https://gcore.jsdelivr.net/gh/tachiyomiorg/tachiyomi-extensions@repo/index.min.json (194ms, unknown-length body)
22:25:39.313 [DefaultDispatcher-worker-6] WARN  io.javalin.Javalin - Uncaught exception
eu.kanade.tachiyomi.network.HttpException: HTTP error 404
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:65)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Changing the url from `https://gcore.jsdelivr.net/gh/tachiyomiorg/tachiyomi-extensions@repo/index.min.json` to `https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json` should be enough to fix it.

**Comment by Robonau** [comment]
use preview and add the extension repo in the config

**Comment by Robonau** [comment]
we will be following tachiyomi/mihon's example and not having a default extension library but allowing users to add a repo themselves

**Comment by wiredmatt** [comment]
Oh I see, would be cool to mention that somewhere. 

For anyone looking, it's in https://suwayomi-webui-preview.github.io/settings/browseSettings

Feel free to close
