### ISSUE TITLE
[Bug] Unable to read manga with very long titles

### ISSUE THREAD

**Issue by xkww3n** [AriaMoradi/Tachidesk#948]
## Device information
- Suwayomi-Server version: 1.0.0
- Server Operating System: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-101-generic x86_64)
- Server Desktop Environment: N/A
- Server JVM version: bundled (Official Docker image)
- Client Operating System: N/A
- Client Web Browser: N/A

## Steps to reproduce
1. Read a manga that has a very long title using Web UI or mobile client. (In my case that is 214 characters)
2. Error occoured.

### Expected behavior
The manga should load normally.

### Actual behavior
Client recieved an error icon (piece of broken paper).

## Other details
Log:
```
java.io.FileNotFoundException: /tmp/Tachidesk/manga-cache/Certain_Source/Certain_Loooooong_Title_Manga/Chapter/024.tmp (File name too long)
tachidesk-1  |  at java.base/java.io.FileOutputStream.open0(Native Method)
tachidesk-1  |  at java.base/java.io.FileOutputStream.open(Unknown Source)
tachidesk-1  |  at java.base/java.io.FileOutputStream.<init>(Unknown Source)
tachidesk-1  |  at java.base/java.io.FileOutputStream.<init>(Unknown Source)
tachidesk-1  |  at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.saveImage(ImageResponse.kt:95)
tachidesk-1  |  at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.getImageResponse(ImageResponse.kt:74)
tachidesk-1  |  at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse$getImageResponse$1.invokeSuspend(ImageResponse.kt)
tachidesk-1  |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
tachidesk-1  |  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
tachidesk-1  |  at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
tachidesk-1  |  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
tachidesk-1  |  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
tachidesk-1  |  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
tachidesk-1  |  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
tachidesk-1  |  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by WROIATE** [comment]
I got the same exception with long title. Is there any way to solve the problem?

**Comment by Robonau** [comment]
this isn't a server issue, its a client issue

**Comment by Robonau** [comment]
i believe the error is an OS error. the different OSs have different limits, 214 chars should be fine in all of them tho.
Windows : 256
Linux: 255 (EXT4: 4096)
Mac: 255

i would expect truncating to 254 chars would fix it (idk about the 214 chars breaking tho, maybe he counted wrong)

**Comment by xkww3n** [comment]
> i believe the error is an OS error. the different OSs have different limits, 214 chars should be fine in all of them tho.
> 
> Windows : 256
> 
> Linux: 255 (EXT4: 4096)
> 
> Mac: 255
> 
> 
> 
> i would expect truncating to 254 chars would fix it (idk about the 214 chars breaking tho, maybe he counted wrong)

I just found that 214 characters is the parent folder's length (Book Name), the full path length is 301 (`/tmp/Tachidesk/manga-cache/<Source Name>/<Book Name>/Chapter/001.tmp`)

**Comment by Well2333** [comment]
same issue here, it's an OS level limit, I think maybe "name mapping" a long name to a short name might fix this issue?

**Comment by Syer10** [comment]
We apply a character limit, but not a byte limit. Linux based filesystems have a 255 byte limit while windows based systems have a 256 char limit.

Since a char does not always equal to 1 byte, that is likely the cause of this issue.

**Comment by Syer10** [comment]
Fixed in https://github.com/Suwayomi/Suwayomi-Server/commit/5bdb945406d92c6ea067d1e7f313a3926bf95631
