### ISSUE TITLE
[Bug] COLAMANGA (onemanhua) throw RuntimeException: Stub!

### ISSUE THREAD

**Issue by WROIATE** [AriaMoradi/Tachidesk#950]
## Device information
- Suwayomi-Server version: v1.0.0-r1411 (use docker stable tag: ghcr.io/suwayomi/tachidesk:stable)
- Server Operating System: docker 
- Client Operating System: Windows
- Client Web Browser: Microsoft Edge 124.0.2478.105

## Steps to reproduce
1. Choose any comic and read
2. Loop loading and log throw throw RuntimeException: Stub!

### Expected behavior
Load comic

### Actual behavior
Throw exception

## Other details
```
03:19:38.517 [DefaultDispatcher-worker-14] WARN notprivacysafe.graphql.execution.SimpleDataFetcherExceptionHandler -- Exception while fetching data (/fetchChapterPages) : Stub!
java.lang.RuntimeException: Stub!
        at android.os.Looper.getMainLooper(Looper.java:30)
        at eu.kanade.tachiyomi.multisrc.colamanga.ColaManga.pageListParse(Unknown Source)
        at eu.kanade.tachiyomi.source.online.ParsedHttpSource.pageListParse(ParsedHttpSource.kt:180)
        at eu.kanade.tachiyomi.source.online.HttpSource$fetchPageList$1.invoke(HttpSource.kt:324)
        at eu.kanade.tachiyomi.source.online.HttpSource$fetchPageList$1.invoke(HttpSource.kt:323)
        at eu.kanade.tachiyomi.source.online.HttpSource.fetchPageList$lambda$8(HttpSource.kt:323)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:39)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda$0(OkHttpExtensions.kt:59)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10423)
        at rx.Observable.subscribe(Observable.java:10390)
        at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:28)
        at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:22)
        at eu.kanade.tachiyomi.source.online.HttpSource.getPageList$suspendImpl(HttpSource.kt:316)
        at eu.kanade.tachiyomi.source.online.HttpSource.getPageList(HttpSource.kt)
        at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownload.fetchPageList(ChapterForDownload.kt:104)
        at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownload.asDownloadReady(ChapterForDownload.kt:62)
        at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownloadKt.getChapterDownloadReady(ChapterForDownload.kt:39)
        at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownloadKt.getChapterDownloadReady$default(ChapterForDownload.kt:32)
        at suwayomi.tachidesk.manga.impl.chapter.ChapterForDownloadKt.getChapterDownloadReadyById(ChapterForDownload.kt:43)
        at suwayomi.tachidesk.graphql.mutations.ChapterMutation$fetchChapterPages$1.invokeSuspend(ChapterMutation.kt:217)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
        at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
        ... 34 common frames omitted

```

**Comment by Robonau** [comment]
is probably just something the colamanga source does that suwayomi doesn't support

**Comment by WROIATE** [comment]
> is probably just something the colamanga source does that suwayomi doesn't support

This plugin is running on Tachiyomi, it means that some Tachiyomi plugin are not supported with suwayomi?

**Comment by Syer10** [comment]
The extension is trying to use a background Android webview to parse the page-list, that we have not been able to create a implementation for.

**Comment by gsxgmpkt9020** [comment]
> Tachiyomi

Yes, we can only use  Tachiyomi app because suwayomi cannot use webview.

**Comment by boyeye** [comment]
I've encountered the same issue and tried various solutions. Currently, the only viable temporary fix is to restart the suwayomi container. However, this isn't an ideal solution because the problem of being unable to pull comics reoccurs about half an hour after restarting.
Colamanga is a manga source I really enjoy. I hope the developers can help resolve the Android WebView support issue. 
Thank you very much!
